// <auto-generated />
namespace Pharmacy5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changing_TransDate_from_DateTime_to_String_Property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changing_TransDate_from_DateTime_to_String_Property));
        
        string IMigrationMetadata.Id
        {
            get { return "201805091438018_-changing_TransDate_from_DateTime_to_String_Property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
