// <auto-generated />
namespace Pharmacy5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changing_expireDate_to_DateTime_from_String : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changing_expireDate_to_DateTime_from_String));
        
        string IMigrationMetadata.Id
        {
            get { return "201805101834269_-changing_expireDate_to_DateTime_from_String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
