// <auto-generated />
namespace Pharmacy5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_creating_database_drug_stockhistroy_order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_creating_database_drug_stockhistroy_order));
        
        string IMigrationMetadata.Id
        {
            get { return "201804061416172_-initial_creating_database_drug_stockhistroy_order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
