// <auto-generated />
namespace Pharmacy5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class normalizing_transaction_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(normalizing_transaction_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201805231422097_-normalizing_transaction_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
