// <auto-generated />
namespace Pharmacy5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class validating_transactions_table_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validating_transactions_table_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201805032049167_-validating_transactions_table_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
