// <auto-generated />
namespace Pharmacy5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adding_searhHistory_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_searhHistory_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201804191111445_-adding_searhHistory_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
