// <auto-generated />
namespace Pharmacy5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editting_drug_model_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editting_drug_model_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201804100026105_-editting_drug_model_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
