// <auto-generated />
namespace Pharmacy5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cleaning_transaction_drugs_and_mainstock_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cleaning_transaction_drugs_and_mainstock_models));
        
        string IMigrationMetadata.Id
        {
            get { return "201805232336175_-cleaning_transaction_drugs_and_mainstock_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
