// <auto-generated />
namespace Pharmacy5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editing_expireDate_to_making_it_nulluable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editing_expireDate_to_making_it_nulluable));
        
        string IMigrationMetadata.Id
        {
            get { return "201805101957225_-editing_expireDate_to_making_it_nulluable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
