// <auto-generated />
namespace Pharmacy5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changing_Dose_datatype_from_float_to_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changing_Dose_datatype_from_float_to_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201805091825105_-changing_Dose_datatype_from_float_to_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
